<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Click Here</name>
   <tag></tag>
   <elementGuidId>54568125-7ff5-4f7c-87f5-180bedf4c4df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[(text() = 'Click Here' or . = 'Click Here') and @ref_element = 'Object Repository/Page_Mailinator (1)/iframe_EMAIL BODY']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://click1.clickrouter.com/redirect?token=a2258079c24c4c50a56b6b1ffb75d6e2&amp;url=https%3A//u6799198.ct.sendgrid.net/wf/click%3Fupn%3DRxQ1t5FTW1OV-2BGSf4yXBfUQFlX-2FcszUJnv5V6VZStfIuCgv7wUBEclzEhqf1aV7R2OR5KA2za0XxYHA1zpRmMr4owiUQPWoGTHs1ksVKV3Q-2BPoIsPf2zzzLeqa7AdS8Li9V6ydTPCQ93qrLGGnKtv2Hx6aAQiNKiyt8tMBOI3utRvpZbH7jHgWWGlNZE6WdeurhSklMZpS781nJE-2FGnOnvdhT7MSTlzbP-2FaWnOyrkP3DfhpYJGhUL8yAX12XquKyrB-2FjGBeD3MMECDn2t5RyPack3bA2d4NEbIaOBgIajKctXKplBJUI6L9slIhqNQBIcvBkKPxZYe-2BqapVHrH3dW-2Br7AN9YBkfAAwxiIZ6IJS00FVrC6eMASMLNWUY0DLrTIJLW3lOhtEkgRuW-2FJPC0j-2BoJRjb1K38DFQ50XB9jc6jJ53uWDsyRYZBxJrEFT-2F4g_DaeO-2BiOMCclMlHPt2i39h9yda0vW2nHLFQHWi-2FYZ-2BaeRYuRE-2FHYY0LkmJVBFOBd-2FXK5MUM7VuAZ2BF-2FWe8s8J4q5SvO4rOgOlPEjWDGUKUdzyvDJaE0nj-2BZjORv6fjXdg5HApbxQ-2BISUGHNkR27dBAhHih2iEUA5d0qDmA2F4AOHIDquEgnBi6B8sdL2ezujPQQWe77DcNYoq3gk0BCZy934-2BY6ycHgVuINN0bj0eDg-3D</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_other</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Click Here</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[2]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/p[3]/a[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Mailinator (1)/iframe_EMAIL BODY</value>
   </webElementProperties>
</WebElementEntity>
